export const GENERIC_ATTRIBUTES = {
  accessory: [
    "Aloha Floral Lei_",
    "Bitcoin Necklace",
    "Gold Oyster Chain",
    "GoldChain",
    "Peace Necklace",
    "Shroom Necklace",
    "SilverChain",
    "silverpepe",
    "Solana Necklace",
  ],
  background: [
    "bamboo",
    "BananaYellow",
    "Beach",
    "Brick(inthe)Wall",
    "Chocolate",
    "FireGradientBackground",
    "Green_",
    "LightBlue",
    "Magenta",
    "Moon",
    "Mustard",
    "OceanBlue",
    "Peach",
    "Purple",
    "Rasta_",
    "SeaFoam",
    "Space",
    "The Shack",
    "Trippy",
    "Undadasea",
  ],
  clothe: [
    "Bikini Pink",
    "Bikini Yellow",
    "CropTop Pink",
    "Earl Bond",
    "Earl Brown",
    "Hawaiin Shirt",
    "One Piece Swimsuit",
    "Overalls Blue",
    "Overalls Tan",
    "Punk Shirt",
    "Rugby Shirt Red",
    "Rugby Shirt",
    "Sleeveless Tshirt",
    "Striped Sweater",
    "SUOC Croptop Beige",
    "SUOC Croptop Grey",
    "SUOC Hoodie",
    "SUOC Shirt White",
    "SUOC Shirt Yellow",
    "Super Woman",
    "Tie Dye Shirt",
    "Too Hot To Handle Women_s Shirt",
    "Traditional Pink Shirt",
    "Traditional Red Shirt",
    "TurtleNeck",
    "Tutu",
    "Wizard Cloak",
    "Women_s Grommet",
    "Women_s shirt Blue",
    "Women_s Shirt Purple",
    "Women_s Shirt Yellow",
  ],
  eye: [
    "3rd Eye Glasses",
    "Anime Eyes Blue",
    "Anime Eyes Brown",
    "Anime Eyes Green",
    "Anime Eyes Pink",
    "Anime Eyes Purple",
    "Crazy Eyes",
    "Disguise Glasses",
    "Fire Eyes",
    "Forgot The Eyedrops",
    "Laser Eyes",
    "Oyster Eyes Blue",
    "Oyster Eyes Brown",
    "Poker Chips",
    "Shuck U Sunnies",
    "Space Eyes",
    "Sunnies Green",
    "Thug Life Glasses_",
    "Trippy Eyes",
    "Yin and Yang Eyes",
  ],
  hat: [
    "1 Gallon Hat",
    "Afro",
    "American Pie",
    "Beanie Black",
    "Beanie Maroon",
    "Beanie Tan",
    "Brainfreeze",
    "Candle and Friends",
    "Cap_",
    "Crab",
    "Crown",
    "Dolphin Hat",
    "Dreads Blonde",
    "Dreads Brown",
    "Dreads Pink",
    "DuRag",
    "Earl Earladome",
    "Earl In The Hat",
    "Fisherman",
    "Gentleman_s Cap",
    "Glove Hat",
    "Halo",
    "Kung Lao Hat",
    "Mind Control",
    "Mullet",
    "Mushroom Hat",
    "Neme",
    "Pigtails Blonde",
    "Pigtails Brown",
    "Raccoon Hat",
    "SHARK",
    "Sombrero",
    "Squid Hat",
    "SUOC Beer Hat",
    "Super Sayan",
    "Surfer Hair Blonde",
    "Surfer Hair Brown",
    "Turkey Hat",
    "Washington Wig",
    "Wizard Hat",
  ],
  mouth: [
    "Big Lips",
    "Boge",
    "Caterpillar Stache",
    "Gandolf Pipe",
    "Lip Ring",
    "Lolipop",
    "Sir Earlington The III Stache",
    "Teeth Smile",
    "Warlord Beard",
    "Wiseman_s beard",
  ],
  shell: [
    "Brown",
    "Camo",
    "Carolina Blue",
    "Coral",
    "Error",
    "Green",
    "Indigo",
    "Lemon",
    "Leopard",
    "Peach",
    "Radioactive",
    "RedSkin",
    "Seafoam_",
    "Soft Pink",
    "Soft Purple",
    "Stone",
    "Tan",
    "Tangerine",
    "Tiger",
    "Zebra",
  ],
};
